chore: denote version number of release name in generate_hashes.py script for developer/debug convenience
had to change the loop of rpm_distros for whatever reason because of this mypy error which i am somehow unable to decipher what it cries about (does distro/releases from the beforehand deb for loop stay in context perhaps?):
__scripts/generate_hashes.py:81: error: Incompatible types in assignment (expression has type "Set[str]", variable has type "List[List[str]]")
__scripts/generate_hashes.py:83: error: Incompatible types in assignment (expression has type "List[str]", variable has type "str")
Found 2 errors in 1 file (checked 1 source file)