fix: do not pass 'base' for pr.edit
otherwise following error occurs:

> GithubException: 422 {"message": "Validation Failed", "errors": [{"message": "There are no new commits between base branch
'checkmk_server_version-autoupdate' and head branch 'checkmk_server_version-autoupdate'", "resource": "PullRequest", "field": "base", "code":
"invalid"}], "documentation_url": "https://docs.github.com/rest/reference/pulls#update-a-pull-request"}

because the purpose of it is (as per "https://docs.github.com/en/rest/pulls/pulls#update-a-pull-request") different than thought:

> The name of the branch you want your changes pulled into. This should be an existing branch on the current repository. You cannot update the base branch on a pull request to point to another repository.